#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: 'arvin'

from template.scanner import router_fingerprint

BASIC_FP = [
    router_fingerprint('R860', 'WWW-Authenticate', 'Basic realm="TP-LINK Router R860"', []),
    router_fingerprint('WR720N', 'WWW-Authenticate', 'Basic realm="150Mbps Wireless N Router TL-WR720N"', []),
    router_fingerprint('TD-8840T 2.0', 'WWW-Authenticate', 'Basic realm="TD-8840T 2.0"', []),
    router_fingerprint('TD-8840T', 'WWW-Authenticate', 'Basic realm="TD-8840T"', []),
    router_fingerprint('TL-WR841HP', 'WWW-Authenticate', 'Basic realm="TP-LINK 300Mbps High Power Wireless N Router TL-WR841HP"', []),
    router_fingerprint('TD-VG3631', 'WWW-Authenticate', 'Basic realm="TP-LINK 300Mbps Wireless N VoIP ADSL2+ Modem Router TD-VG3631"', []),
    router_fingerprint('Archer C5', 'WWW-Authenticate', 'Basic realm="TP-LINK AC1200 Wireless Dual Band Gigabit Router Archer C5"', []),
    router_fingerprint('Archer C8', 'WWW-Authenticate', 'Basic realm="TP-LINK AC1750 Wireless Dual Band Gigabit Router Archer C8"', []),
    router_fingerprint('Archer C9', 'WWW-Authenticate', 'Basic realm="TP-LINK AC1750 Wireless Dual Band Gigabit Router Archer C9"', []),
    router_fingerprint('TD-8840T', 'WWW-Authenticate', 'Basic realm="TP-LINK ADSL2+ Modem Router TD-8840T"', []),
    router_fingerprint('R600VPN', 'WWW-Authenticate', 'Basic realm="TP-LINK Gigabit Broadband VPN Router R600VPN"', []),
    router_fingerprint('WR842ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Multi-Function Wireless N Router WR842ND"', []),
    router_fingerprint('WA7210N', 'WWW-Authenticate', 'Basic realm="TP-LINK Outdoor Wireless Access Point WA7210N"', []),
    router_fingerprint('MR3020', 'WWW-Authenticate', 'Basic realm="TP-LINK Portable Wireless N 3G/4G Router MR3020"', []),
    router_fingerprint('MR3040', 'WWW-Authenticate', 'Basic realm="TP-LINK Portable Wireless N 3G/4G Router MR3040"', []),
    router_fingerprint('WA501G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless AP WA501G"', []),
    router_fingerprint('WA5110G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless AP WA5110G"', []),
    router_fingerprint('WA5210G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless AP WA5210G"', []),
    router_fingerprint('WA601G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless AP WA601G"', []),
    router_fingerprint('Archer C5', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Gigabit Router Archer C5"', []),
    router_fingerprint('Archer C7', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Gigabit Router Archer C7"', []),
    router_fingerprint('WDR3600', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Gigabit Router WDR3600"', []),
    router_fingerprint('WDR4300', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Gigabit Router WDR4300"', []),
    router_fingerprint('WDR4900', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Gigabit Router WDR4900"', []),
    router_fingerprint('WDR3500', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Dual Band Router WDR3500"', []),
    router_fingerprint('WR340G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless G Router WR340G"', []),
    router_fingerprint('WA730RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Access Point WA730RE"', []),
    router_fingerprint('WR740N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Router WR740N"', []),
    router_fingerprint('WR740N/WR741ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Router WR740N/WR741ND"', []),
    router_fingerprint('WR741N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Router WR741N"', []),
    router_fingerprint('WR741ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Router WR741ND"', []),
    router_fingerprint('WR743ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Lite N Router WR743ND"', []),
    router_fingerprint('MR3420', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N 3G Router MR3420"', []),
    router_fingerprint('MR3420', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N 3G/4G Router MR3420"', []),
    router_fingerprint('WA701ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Access Point WA701ND"', []),
    router_fingerprint('WA801N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Access Point WA801N"', []),
    router_fingerprint('WA901N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Access Point WA901N"', []),
    router_fingerprint('WA901ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Access Point WA901ND"', []),
    router_fingerprint('WR1042ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Gigabit Router WR1042ND"', []),
    router_fingerprint('WR1043N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Gigabit Router WR1043N"', []),
    router_fingerprint('WR1043ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Gigabit Router WR1043ND"', []),
    router_fingerprint('WR1045ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Gigabit Router WR1045ND"', []),
    router_fingerprint('WR2543ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Gigabit Router WR2543ND"', []),
    router_fingerprint('WR702N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Nano Router WR702N"', []),
    router_fingerprint('WA830RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Range Extender WA830RE"', []),
    router_fingerprint('WA840RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR840N"', []),
    router_fingerprint('WR841N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR841N"', []),
    router_fingerprint('WR843ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR843ND"', []),
    router_fingerprint('WR940N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR940N"', []),
    router_fingerprint('WR941N', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR941N"', []),
    router_fingerprint('WR941ND', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless N Router WR941ND"', []),
    router_fingerprint('WA750RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Range Extender WA750RE"', []),
    router_fingerprint('WA850RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Range Extender WA850RE"', []),
    router_fingerprint('WA860RE', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Range Extender WA860RE"', []),
    router_fingerprint('WR541G/542G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Router WR541G/542G"', []),
    router_fingerprint('WR543G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Router WR543G"', []),
    router_fingerprint('WR641G/642G', 'WWW-Authenticate', 'Basic realm="TP-LINK Wireless Router WR641G/642G"', []),
]

HTTP_FP = [
    router_fingerprint('TL-R470T+', 'SERVER', 'TP-LINK SMB TL-R470T+router_fingerprint(UN), UPnP/1.0', []),
    router_fingerprint('TL-R480T+', 'SERVER', 'TP-LINK SMB TL-R480T+router_fingerprint(UN), UPnP/1.0', []),
    router_fingerprint('Range Extender', 'SERVER', 'TP-LINK HTTPD/1.0', []),
]

